### ISSUE TITLE
Multiple instances of this action in the same workflow overwrite each other's PR comment

### ISSUE THREAD

**Issue by mike-schenk** [im-open/process-code-coverage-summary#7]
https://github.com/im-open/process-code-coverage-summary/blob/7e5767976f802d1c43ea8280de707c80f1171084/main.js#L38

When I have actions for both Jest and Dotnet tests and each has a corresponding process-code-coverage-summary action that is set to `create-pr-comment: true` and the default `update-comment-if-one-exists: true`, the PR comments only show whichever one finished last.

**Comment by danielle-casella-adams** [comment]
This should be addressed in #10 by using the update-comment-key argument.
